### ISSUE TITLE
This tool decompress the main file to what file type?

### ISSUE THREAD

**Issue by zellfy** [0CBH0/nsnsotool#2]
Thank you.

**Comment by zellfy** [comment]
I'm trying to edit the main file in the exefs folder which type is nso. But there is just one tool seems to work called nx2elf, but it doesn't work on this file. So I am seeking for another tool.

**Comment by 0CBH0** [comment]
This tool simply decompresses the compressed segments of nso file into uncompressed segments for direct editing. 
So it is still a nso file after decompressing.
I apologize for the late reply 😩
